version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/var/www/frontend/public
      - ./backend:/var/www/backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
