services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/backend
      - ./frontend/public:/backend/public
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: app-network
