services:
  fastify:
    container_name: fastify
    restart: always
    build: ./backend
    ports: ["8080:80"]
    volumes:
      - ./backend:/backend
      - ./frontend/public:/backend/public
    networks: [transcendence]
    depends_on:
      # - tailwind
      - frontend

  frontend:
    container_name: frontend
    build: ./frontend
    networks: [transcendence]
    volumes:
      - ./frontend:/frontend
    restart: always

  # tailwind:
  #   container_name: tailwind
  #   build: ./tailwind
  #   networks: [transcendence]
  #   volumes:
  #     - ./frontend:/frontend
  #   restart: always

networks:
  transcendence:
    name: transcendence
